name: Test

on:
  push:
    [ ]
  pull_request:
    [ ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: |
          echo $INFURA_API_KEY
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      - run: yarn test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
